# Generated by Django 4.1.3 on 2022-12-04 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0003_alter_guitar_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guitar',
            old_name='brand',
            new_name='model',
        ),
    ]
