# Generated by Django 4.1.3 on 2022-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0004_rename_brand_guitar_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guitar',
            name='body',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='fretboard',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='type',
            field=models.CharField(choices=[('Acoustic', 'Acoustic'), ('Electric', 'Electric'), ('Bass', 'Bass')], max_length=50),
        ),
    ]
