# Generated by Django 4.1.3 on 2022-12-04 20:57

from django.db import migrations, models
import music_store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50)),
                ('keys', models.PositiveIntegerField(validators=[music_store.validators.validate_keys_number])),
                ('sounds', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images', validators=[music_store.validators.validate_file_size])),
                ('price', models.FloatField()),
            ],
        ),
    ]
