# Generated by Django 4.1.3 on 2022-12-05 12:45

from django.db import migrations, models
import music_store.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Strings', 'Strings'), ('Pick', 'Pick'), ('Cymbal', 'Cymbal'), ('Drum', 'Drum')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images', validators=[music_store.validators.validate_file_size])),
                ('price', models.FloatField()),
            ],
        ),
    ]
